# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 17:25
from __future__ import unicode_literals

import PDF_Merge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=PDF_Merge.models.upload_to)),
            ],
        ),
    ]
