# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20170303_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
